//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLChiTieuEntities1 : DbContext
    {
        public QLChiTieuEntities1()
            : base("name=QLChiTieuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HEO> HEOs { get; set; }
        public virtual DbSet<Nhom> Nhoms { get; set; }
        public virtual DbSet<SO_GIAO_DICH> SO_GIAO_DICH { get; set; }
        public virtual DbSet<SO_NO> SO_NO { get; set; }
        public virtual DbSet<USER_GIAO_DICH> USER_GIAO_DICH { get; set; }
        public virtual DbSet<USER_VI> USER_VI { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vi> Vis { get; set; }
    }
}
