//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLChiTieuEntities : DbContext
    {
        public QLChiTieuEntities()
            : base("QLChiTieuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HEO> HEOs { get; set; }
        public virtual DbSet<Nhom> Nhoms { get; set; }
        public virtual DbSet<SO_GIAO_DICH> SO_GIAO_DICH { get; set; }
        public virtual DbSet<SO_NO> SO_NO { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vi> Vis { get; set; }
    
        public virtual int uspAddUser(string pEmail, string pPassword, string pTen, Nullable<System.DateTime> pDob, ObjectParameter responseMessage)
        {
            var pEmailParameter = pEmail != null ?
                new ObjectParameter("pEmail", pEmail) :
                new ObjectParameter("pEmail", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            var pTenParameter = pTen != null ?
                new ObjectParameter("pTen", pTen) :
                new ObjectParameter("pTen", typeof(string));
    
            var pDobParameter = pDob.HasValue ?
                new ObjectParameter("pDob", pDob) :
                new ObjectParameter("pDob", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspAddUser", pEmailParameter, pPasswordParameter, pTenParameter, pDobParameter, responseMessage);
        }
    
        public virtual int uspLogin(string pEmail, string pPassword, ObjectParameter responseMessage)
        {
            var pEmailParameter = pEmail != null ?
                new ObjectParameter("pEmail", pEmail) :
                new ObjectParameter("pEmail", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspLogin", pEmailParameter, pPasswordParameter, responseMessage);
        }
    }
}
