//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ngan_Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ngan_Sach()
        {
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public int Ten { get; set; }
        public int IdNhom { get; set; }
        public int SoTien { get; set; }
        public int SoTienConLai { get; set; }
        public decimal PhanTram { get; set; }
        public Nullable<System.DateTime> Ngay_Bat_Dau { get; set; }
        public Nullable<System.DateTime> Ngay_Ket_Thuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
