//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLChiTieuEntities : DbContext
    {
        public QLChiTieuEntities()
            : base("name=QLChiTieuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HEO> HEOs { get; set; }
        public virtual DbSet<Nhom> Nhoms { get; set; }
        public virtual DbSet<SO_GIAO_DICH> SO_GIAO_DICH { get; set; }
        public virtual DbSet<SO_NO> SO_NO { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vi> Vis { get; set; }
    
        public virtual int uspAddUser(string pUsername, string pPassword, string pTen, Nullable<System.DateTime> pDob, ObjectParameter responseMessage)
        {
            var pUsernameParameter = pUsername != null ?
                new ObjectParameter("pUsername", pUsername) :
                new ObjectParameter("pUsername", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            var pTenParameter = pTen != null ?
                new ObjectParameter("pTen", pTen) :
                new ObjectParameter("pTen", typeof(string));
    
            var pDobParameter = pDob.HasValue ?
                new ObjectParameter("pDob", pDob) :
                new ObjectParameter("pDob", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspAddUser", pUsernameParameter, pPasswordParameter, pTenParameter, pDobParameter, responseMessage);
        }
    
        public virtual int uspLogin(string pUsername, string pPassword, ObjectParameter responseMessage)
        {
            var pUsernameParameter = pUsername != null ?
                new ObjectParameter("pUsername", pUsername) :
                new ObjectParameter("pUsername", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspLogin", pUsernameParameter, pPasswordParameter, responseMessage);
        }
    
        public virtual int uspModifyPassWord(Nullable<int> pId, string oldPassword, string newPassword, ObjectParameter responseMessage)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            var oldPasswordParameter = oldPassword != null ?
                new ObjectParameter("oldPassword", oldPassword) :
                new ObjectParameter("oldPassword", typeof(string));
    
            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("newPassword", newPassword) :
                new ObjectParameter("newPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspModifyPassWord", pIdParameter, oldPasswordParameter, newPasswordParameter, responseMessage);
        }
    
        public virtual int uspModifyUserName(Nullable<int> pId, string uPassword, string nUsername, ObjectParameter responseMessage)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            var uPasswordParameter = uPassword != null ?
                new ObjectParameter("uPassword", uPassword) :
                new ObjectParameter("uPassword", typeof(string));
    
            var nUsernameParameter = nUsername != null ?
                new ObjectParameter("nUsername", nUsername) :
                new ObjectParameter("nUsername", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspModifyUserName", pIdParameter, uPasswordParameter, nUsernameParameter, responseMessage);
        }
    
        public virtual int uspThemGiaoDich(Nullable<int> pIdUser, Nullable<int> pVi, Nullable<int> pIdNhom, Nullable<int> pSoTien, string pGhiChu, string pNguoiLienQuan, Nullable<System.DateTime> pNgay, ObjectParameter responseMessage)
        {
            var pIdUserParameter = pIdUser.HasValue ?
                new ObjectParameter("pIdUser", pIdUser) :
                new ObjectParameter("pIdUser", typeof(int));
    
            var pViParameter = pVi.HasValue ?
                new ObjectParameter("pVi", pVi) :
                new ObjectParameter("pVi", typeof(int));
    
            var pIdNhomParameter = pIdNhom.HasValue ?
                new ObjectParameter("pIdNhom", pIdNhom) :
                new ObjectParameter("pIdNhom", typeof(int));
    
            var pSoTienParameter = pSoTien.HasValue ?
                new ObjectParameter("pSoTien", pSoTien) :
                new ObjectParameter("pSoTien", typeof(int));
    
            var pGhiChuParameter = pGhiChu != null ?
                new ObjectParameter("pGhiChu", pGhiChu) :
                new ObjectParameter("pGhiChu", typeof(string));
    
            var pNguoiLienQuanParameter = pNguoiLienQuan != null ?
                new ObjectParameter("pNguoiLienQuan", pNguoiLienQuan) :
                new ObjectParameter("pNguoiLienQuan", typeof(string));
    
            var pNgayParameter = pNgay.HasValue ?
                new ObjectParameter("pNgay", pNgay) :
                new ObjectParameter("pNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspThemGiaoDich", pIdUserParameter, pViParameter, pIdNhomParameter, pSoTienParameter, pGhiChuParameter, pNguoiLienQuanParameter, pNgayParameter, responseMessage);
        }
    
        public virtual int uspThemKhoanChoVay(Nullable<int> pId_User, Nullable<int> pId_Vi, string pPerson, Nullable<int> pSoTien, string pGhiChu, Nullable<System.DateTime> pNgayVay, ObjectParameter responseMessage)
        {
            var pId_UserParameter = pId_User.HasValue ?
                new ObjectParameter("pId_User", pId_User) :
                new ObjectParameter("pId_User", typeof(int));
    
            var pId_ViParameter = pId_Vi.HasValue ?
                new ObjectParameter("pId_Vi", pId_Vi) :
                new ObjectParameter("pId_Vi", typeof(int));
    
            var pPersonParameter = pPerson != null ?
                new ObjectParameter("pPerson", pPerson) :
                new ObjectParameter("pPerson", typeof(string));
    
            var pSoTienParameter = pSoTien.HasValue ?
                new ObjectParameter("pSoTien", pSoTien) :
                new ObjectParameter("pSoTien", typeof(int));
    
            var pGhiChuParameter = pGhiChu != null ?
                new ObjectParameter("pGhiChu", pGhiChu) :
                new ObjectParameter("pGhiChu", typeof(string));
    
            var pNgayVayParameter = pNgayVay.HasValue ?
                new ObjectParameter("pNgayVay", pNgayVay) :
                new ObjectParameter("pNgayVay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspThemKhoanChoVay", pId_UserParameter, pId_ViParameter, pPersonParameter, pSoTienParameter, pGhiChuParameter, pNgayVayParameter, responseMessage);
        }
    
        public virtual int uspThemKhoanTietKiem(Nullable<int> pIdUser, Nullable<int> pIdKhoanTK, Nullable<int> pIdVi, Nullable<int> pSoTien, ObjectParameter responseMessage)
        {
            var pIdUserParameter = pIdUser.HasValue ?
                new ObjectParameter("pIdUser", pIdUser) :
                new ObjectParameter("pIdUser", typeof(int));
    
            var pIdKhoanTKParameter = pIdKhoanTK.HasValue ?
                new ObjectParameter("pIdKhoanTK", pIdKhoanTK) :
                new ObjectParameter("pIdKhoanTK", typeof(int));
    
            var pIdViParameter = pIdVi.HasValue ?
                new ObjectParameter("pIdVi", pIdVi) :
                new ObjectParameter("pIdVi", typeof(int));
    
            var pSoTienParameter = pSoTien.HasValue ?
                new ObjectParameter("pSoTien", pSoTien) :
                new ObjectParameter("pSoTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspThemKhoanTietKiem", pIdUserParameter, pIdKhoanTKParameter, pIdViParameter, pSoTienParameter, responseMessage);
        }
    
        public virtual int uspThemKhoanVay(Nullable<int> pId_User, Nullable<int> pId_Vi, string pPerson, Nullable<int> pSoTien, string pGhiChu, Nullable<System.DateTime> pNgayVay, ObjectParameter responseMessage)
        {
            var pId_UserParameter = pId_User.HasValue ?
                new ObjectParameter("pId_User", pId_User) :
                new ObjectParameter("pId_User", typeof(int));
    
            var pId_ViParameter = pId_Vi.HasValue ?
                new ObjectParameter("pId_Vi", pId_Vi) :
                new ObjectParameter("pId_Vi", typeof(int));
    
            var pPersonParameter = pPerson != null ?
                new ObjectParameter("pPerson", pPerson) :
                new ObjectParameter("pPerson", typeof(string));
    
            var pSoTienParameter = pSoTien.HasValue ?
                new ObjectParameter("pSoTien", pSoTien) :
                new ObjectParameter("pSoTien", typeof(int));
    
            var pGhiChuParameter = pGhiChu != null ?
                new ObjectParameter("pGhiChu", pGhiChu) :
                new ObjectParameter("pGhiChu", typeof(string));
    
            var pNgayVayParameter = pNgayVay.HasValue ?
                new ObjectParameter("pNgayVay", pNgayVay) :
                new ObjectParameter("pNgayVay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspThemKhoanVay", pId_UserParameter, pId_ViParameter, pPersonParameter, pSoTienParameter, pGhiChuParameter, pNgayVayParameter, responseMessage);
        }
    
        public virtual int uspThemTietKiem(Nullable<int> pIdUser, string pTenKhoanTk, string pMucDich, Nullable<int> pMucTieu, Nullable<System.DateTime> pNgayKT, ObjectParameter responseMessage)
        {
            var pIdUserParameter = pIdUser.HasValue ?
                new ObjectParameter("pIdUser", pIdUser) :
                new ObjectParameter("pIdUser", typeof(int));
    
            var pTenKhoanTkParameter = pTenKhoanTk != null ?
                new ObjectParameter("pTenKhoanTk", pTenKhoanTk) :
                new ObjectParameter("pTenKhoanTk", typeof(string));
    
            var pMucDichParameter = pMucDich != null ?
                new ObjectParameter("pMucDich", pMucDich) :
                new ObjectParameter("pMucDich", typeof(string));
    
            var pMucTieuParameter = pMucTieu.HasValue ?
                new ObjectParameter("pMucTieu", pMucTieu) :
                new ObjectParameter("pMucTieu", typeof(int));
    
            var pNgayKTParameter = pNgayKT.HasValue ?
                new ObjectParameter("pNgayKT", pNgayKT) :
                new ObjectParameter("pNgayKT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspThemTietKiem", pIdUserParameter, pTenKhoanTkParameter, pMucDichParameter, pMucTieuParameter, pNgayKTParameter, responseMessage);
        }
    
        public virtual int uspThemVi(Nullable<int> pIdUser, string pTenVi, Nullable<int> pSoTien, ObjectParameter responseMessage)
        {
            var pIdUserParameter = pIdUser.HasValue ?
                new ObjectParameter("pIdUser", pIdUser) :
                new ObjectParameter("pIdUser", typeof(int));
    
            var pTenViParameter = pTenVi != null ?
                new ObjectParameter("pTenVi", pTenVi) :
                new ObjectParameter("pTenVi", typeof(string));
    
            var pSoTienParameter = pSoTien.HasValue ?
                new ObjectParameter("pSoTien", pSoTien) :
                new ObjectParameter("pSoTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspThemVi", pIdUserParameter, pTenViParameter, pSoTienParameter, responseMessage);
        }
    
        public virtual int uspThuNo(Nullable<int> idUser, Nullable<int> idKhoanChoVay, ObjectParameter responseMessage)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("IdUser", idUser) :
                new ObjectParameter("IdUser", typeof(int));
    
            var idKhoanChoVayParameter = idKhoanChoVay.HasValue ?
                new ObjectParameter("IdKhoanChoVay", idKhoanChoVay) :
                new ObjectParameter("IdKhoanChoVay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspThuNo", idUserParameter, idKhoanChoVayParameter, responseMessage);
        }
    
        public virtual int uspTraNo(Nullable<int> idUser, Nullable<int> idKhoanVay, ObjectParameter responseMessage)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("IdUser", idUser) :
                new ObjectParameter("IdUser", typeof(int));
    
            var idKhoanVayParameter = idKhoanVay.HasValue ?
                new ObjectParameter("IdKhoanVay", idKhoanVay) :
                new ObjectParameter("IdKhoanVay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspTraNo", idUserParameter, idKhoanVayParameter, responseMessage);
        }
    }
}
