//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_NO
    {
        public int STT { get; set; }
        public int ID_GIAO_DICH { get; set; }
        public string LOAI { get; set; }
        public string PERSON { get; set; }
        public System.DateTime NGAY { get; set; }
    
        public virtual SO_GIAO_DICH SO_GIAO_DICH { get; set; }
    }
}
