//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_GIAO_DICH
    {
        public int ID_GIAO_DICH { get; set; }
        public int ID_USER { get; set; }
    }
}
